name: testdata
top_dir: testdata
scheme: testdata/scheme.txt
R1_fastq: testdata/fastq/raw/R1.fastq.gz
R2_fastq: testdata/fastq/raw/R2.fastq.gz
cutadapt_r1_adapter_seq_to_trim: AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTT
cutadapt_r2_adapter_seq_to_trim: TACCCTTCGCTTCACACACAAGGGGAAAGAGTGTAGATCTCGGTGGTCGC
STAR_index: /oak/stanford/groups/khavari/users/dfporter/pre_2021_projects/genome/GRCh38.gencode.29/star_index/
STAR: STAR
clipper: /storage/khavari/data/dfporter/anaconda3/envs/clipper3/bin/clipper
feature_gtf: assets/reference/gencode.v29.basic.annotation.gtf
