name: testdata
top_dir: testdata
scheme: testdata/samples.txt
Fastq_folder: testdata/fastq/raw
cutadapt_r1_adapter_seq_to_trim: AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTT
cutadapt_r2_adapter_seq_to_trim: TACCCTTCGCTTCACACACAAGGGGAAAGAGTGTAGATCTCGGTGGTCGC
L5_inline: BBBBBBNNNNNNN
L3_inline: BBB
STAR_index: /oak/stanford/groups/khavari/users/dfporter/pre_2021_projects/genome/GRCh38.gencode.29/star_index/
STAR: STAR
clipper: /storage/khavari/data/dfporter/anaconda3/envs/clipper3/bin/clipper
feature_gtf: assets/reference/gencode.v29.basic.annotation.gtf
genomic_fasta: assets/reference/GRCh38.primary_assembly.genome.fa
