name: easyclip-env
channels:
  #- conda-forge
  - bioconda
dependencies:
  - python
  - numpy
  - dill
  - scipy
  - statsmodels
  - scikit-learn
  - pandas
  - openpyxl
  - deeptools=3.3.0
  - bedtools
  - ucsc-bedsort
  - ucsc-bedgraphtobigwig
  - gffutils
  - cutadapt
  - HTSeq
  - pyBigWig
  - pysam
  - snakemake
  - star=2.7.1a
  - samtools
